DROP TABLE credential CASCADE;
DROP TABLE users CASCADE;
DROP TABLE password CASCADE;
DROP TABLE rsa_keys CASCADE;

DROP SEQUENCE users_id CASCADE;
DROP SEQUENCE password_id CASCADE;
DROP SEQUENCE credential_id CASCADE;
DROP SEQUENCE rsa_keys_id CASCADE;