DROP TABLE credential CASCADE;
DROP TABLE users CASCADE;
DROP TABLE password CASCADE;
DROP TABLE public_key CASCADE;
DROP TABLE private_key CASCADE;

DROP SEQUENCE users_id CASCADE;
DROP SEQUENCE password_id CASCADE;
DROP SEQUENCE credential_id CASCADE;
DROP SEQUENCE public_key_id CASCADE;
DROP SEQUENCE private_key_id CASCADE;
